name: Release PR
description: Open or update a release PR to bump and tag the version
author: Chawye Hsu
branding:
  icon: git-pull-request
  color: white

inputs:
  private-key:
    description: Private key of release maid bot to open release PRs
    required: true

runs:
  using: composite
  steps:
    - name: Mint Release Maid Token
      uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
      id: app-token
      if: github.repository_owner == 'chawyehsu' && github.event_name == 'push'
      with:
        client-id: "Iv23lifYx9gjogZQFf6X"
        private-key: ${{ inputs.private-key }}
        owner: ${{ github.repository_owner }}
        repositories: ${{ github.event.repository.name }}

    - name: Run Release Please
      uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
      with:
        token: ${{ steps.app-token.outputs.token }}
        skip-github-release: true

    - name: Create Release Tag
      id: create-tag
      if: "${{ success() && startsWith(github.event.head_commit.message, 'chore(main): release') }}"
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
      shell: bash
      run: |
        set -euo pipefail
        API='repos/${{ github.repository_owner }}/${{ github.event.repository.name }}'
        CONT="${API}/contents/.release-please-manifest.json"
        VERSION=$(gh api ${CONT} -H "Accept: application/vnd.github.raw" | jq -r '."."')
        TAG="v${VERSION}"
        echo "tag=${TAG}" >> "$GITHUB_OUTPUT"
        if gh api --silent "${API}/git/refs/tags/${TAG}" >/dev/null 2>&1; then
          echo "Tag ${TAG} already exists, skip."
          exit 0
        fi
        gh api -X POST "${API}/git/refs" -f ref="refs/tags/${TAG}" \
          -f sha="${{ github.sha }}"
        echo "Tag ${TAG} created successfully."

    - name: Update Release PR Labels
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
      shell: bash
      run: |
        set -euo pipefail
        TAG="${{ steps.create-tag.outputs.tag }}"
        REPO='${{ github.repository_owner }}/${{ github.event.repository.name }}'
        PENDING='autorelease: pending'
        TAGGED='autorelease: tagged'
        PR_JSON=$(gh pr -R "${REPO}" list \
          --label "${PENDING}" --state all \
          --json number,title)
        PRS=$(echo "${PR_JSON}" | jq -r --arg tag "${TAG}" \
          '[.[] | select(.title | contains($tag)) | .number] | .[]')
        if [ -z "${PRS}" ]; then
          echo "No release PR with '${PENDING}' label and '${TAG}' in title found, skip."
          exit 0
        fi
        while IFS= read -r PR; do
          gh pr -R "${REPO}" edit "${PR}" \
            --remove-label "${PENDING}" \
            --add-label "${TAGGED}"
          echo "Release PR #${PR} labels updated."
        done <<< "${PRS}"
